runtime: go123  # or go120, go119 depending on your version
handlers:
  - url: /.*
    script: auto

env_variables:
  GCP_PROJECT_ID: aicoexist-446217
  DB_HOST: 46.202.93.117
  DB_USER: admin
  DB_PASSWORD: admin
  DB_PORT: 5432
  DB_NAME: aisense_portal
  SERVICE_ACCOUNT_JSON_FILE_PATH: assets/service-account.json
  GIN_MODE: release